### ISSUE TITLE
Tracker Network Protocol Changes

### ISSUE THREAD

**Issue by renfei** [pradt2/always-online-torrent-trackers#1]
https://github.com/pradt2/always-online-torrent-trackers/blob/bf684616fd9732be752d84f88dd58a671eee3f42/candidates.txt#L407

Hello,

The Tracker network protocol becomes:

* udp://tracker.renfei.net:8080/announce 
* http://tracker.renfei.net:8080/announce

**Comment by pradt2** [comment]
Updated, thanks.
